language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    # Android SDK Tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-23.0.3
    # The SDK version used to compile your project
    - android-23
    # Additional components
    - extra-android-support
    - extra-android-m2repository

before_install:
- chmod +x .utility/initiate-publish.sh
- openssl aes-256-cbc -K $encrypted_ca35921423ab_key -iv $encrypted_ca35921423ab_iv -in .utility/signingkey.gpg.enc -out .utility/signingkey.gpg -d

script: ./gradlew testDebugUnitTest

after_success:
- ".utility/initiate-publish.sh"