language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    # Android SDK Tools
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-30.0.3
    # The SDK version used to compile your project
    - android-30
    # Additional components
    - extra-android-support
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

script: ./gradlew test