# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: mangopay2-cardregistration-android-kit-cd

on:
  push:
    branches:
      # push on master branch
      - master
      # push on a feature branch
      - feature/*
      # push on a bugfix branch
      - bugfix/*
    tags:
      # It pushes any tags that contain a v. ex: v1.16.1
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Decode secring.gpg
#        run: |
#          mkdir -p .gnupg/
#          chmod 700 .gnupg
#          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > .gnupg/secring.gpg.b64
#          base64 -d .gnupg/secring.gpg.b64 > .gnupg/secring.gpg
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Export GPG key
        run: gpg --pinentry-mode=loopback --passphrase ${SIGNING_PASSWORD} --keyring secring.gpg --export-secret-key 117407B30B32E5E1380EE2FC6E7E86304C9F8BAF > .utility/signingkey.gpg
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Give permissions to file
        run: chmod +x .utility/initiate-publish.sh
      - name: Publish
        run: ./.utility/initiate-publish.sh
        env:
          SIGNING_PASSWORD: ${{ secrets.PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Close and publish
        run: ./gradlew closeAndReleaseRepository -PnexusUsername=${{ secrets.MAVEN_USERNAME }} -PnexusPassword=${{ secrets.MAVEN_PASSWORD }}